version: '3'
# this just tells you the services to run
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile   # This will use the Dockerfile you just created
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toolroom
      MYSQL_USER: toolmaster
      MYSQL_PASSWORD: dLTvu]eJzwAd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  mysql_data: